import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:darawalkaab/l10n/app_localizations.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final backgroundColor = isDark
        ? const Color(0xFF121212)
        : const Color(0xFFF5F7FA);
    final cardColor = isDark ? const Color(0xFF2C2C2C) : Colors.white;
    final textColor = isDark ? Colors.white : Colors.black;
    final subTextColor = isDark ? Colors.grey[400]! : Colors.grey[700]!;

    return Scaffold(
      backgroundColor: backgroundColor,
      appBar: AppBar(
        title: Text(
          AppLocalizations.of(context)!.privacyPolicy,
          style: GoogleFonts.poppins(
            color: textColor,
            fontWeight: FontWeight.w600,
            fontSize: 18,
          ),
        ),
        centerTitle: true,
        backgroundColor: Theme.of(context).appBarTheme.backgroundColor,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: textColor),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: cardColor,
            borderRadius: BorderRadius.circular(16),
            boxShadow: [
              if (!isDark)
                const BoxShadow(
                  color: Color.fromRGBO(0, 0, 0, 0.05),
                  blurRadius: 10,
                  offset: Offset(0, 4),
                ),
            ],
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                "Tusiye App Privacy Policy",
                style: GoogleFonts.poppins(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  color: textColor,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                "Effective Date: June 08, 2026",
                style: GoogleFonts.poppins(
                  fontSize: 12,
                  color: Colors.grey[500],
                  fontWeight: FontWeight.w500,
                ),
              ),
              const Divider(height: 32, thickness: 1),
              
              _buildSectionContent(
                "Tusiye App (\"we,\" \"us,\" or \"our\") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application, Tusiye App (the \"App\" or \"Service\").",
                subTextColor,
              ),
              _buildSectionContent(
                "Please read this Privacy Policy carefully. By downloading, accessing, or using the Service, you consent to the collection, transfer, storage, disclosure, and use of your information as described in this Privacy Policy. If you do not agree with the terms of this Privacy Policy, please do not download or use the App.",
                subTextColor,
              ),

              _buildSectionTitle("1. Definitions", textColor),
              _buildSectionContent(
                "• Account: A unique account created for you to access our Service or parts of our Service.\n"
                "• Device: Any device that can access the Service, such as a mobile phone, tablet, or digital computer.\n"
                "• Personal Data: Any information that relates to an identified or identifiable individual.\n"
                "• Service: The Tusiye App mobile application.\n"
                "• Service Provider: Any natural or legal person who processes data on behalf of the App (such as hosting, database, and analytics providers).\n"
                "• Usage Data: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
                subTextColor,
              ),

              _buildSectionTitle("2. Information We Collect", textColor),
              _buildSubSectionTitle("A. Information You Voluntarily Provide", textColor),
              _buildSectionContent(
                "• Account Registration Information: When you sign up for an Account, we collect your email address, username, display name, and password (which is securely hashed and encrypted).\n"
                "• Profile Metadata: If you customize your profile, we collect your profile picture, biographical description, and related settings.\n"
                "• User-Generated Content: We collect the contents of posts you publish (such as \"Jump Posts\" containing road condition descriptions, street names, and metadata), media uploads (photos and videos), comments, replies, and list interactions (such as your designated favorite locations and followed profiles).\n"
                "• Communications: If you contact us directly for support or inquiries, we collect your email address, name, and any information you choose to provide in your message.",
                subTextColor,
              ),
              
              _buildSubSectionTitle("B. Information Collected Automatically", textColor),
              _buildSectionContent(
                "• Precise and Coarse Location Data: With your explicit consent, we collect precise location data (GPS coordinates) from your mobile device using your device’s location services. We use this data to calculate your distance to nearby automotive services (such as gas stations and repair shops), display nearby road condition reports, and overlay coordinates on the map. You can grant or revoke location access at any time through your mobile device's settings.\n"
                "• Device and Usage Information: When you use the App, we automatically collect certain technical details, including IP address, device model, manufacturer, operating system version, unique device identifiers (such as Android ID or IDFV), and app crash/telemetry logs.\n"
                "• Camera and Media Access: To upload photos or videos to \"Jump Posts\" or to download shared media, the App requests permission to access your device’s Camera and Photo/Media Library.",
                subTextColor,
              ),

              _buildSectionTitle("3. How We Process and Use Your Information", textColor),
              _buildSectionContent(
                "We process your Personal Data under valid legal bases (including performance of a contract with you, your consent, and our legitimate business interests) for the following purposes:\n"
                "• To Provide, Maintain, and Improve the Service: Managing your account, enabling core features, and optimizing app performance.\n"
                "• To Deliver Location-Based Services: Calculating and displaying maps, driving directions, and localized road hazard alerts.\n"
                "• To Foster User Interaction: Allowing you to publish updates, follow other users, and post comments or replies.\n"
                "• To Send Administrative and Local Alerts: Communicating app updates, support responses, and local push notifications.\n"
                "• To Ensure Safety and Compliance: Detecting, preventing, and addressing fraud, copyright violations, security breaches, and technical issues.",
                subTextColor,
              ),

              _buildSectionTitle("4. Third-Party Service Providers and Data Disclosures", textColor),
              _buildSectionContent(
                "We do not sell, rent, or trade your Personal Data. To deliver our services, we share information with trusted third-party providers who process data on our behalf:\n"
                "• Supabase (Backend Infrastructure & Authentication): We use Supabase to host our database, manage secure authentication, and store media uploads. Your user profile, hashed passwords, and uploaded content are securely stored on their servers.\n"
                "• Google Maps SDK: We integrate Google Maps to render maps and compute route coordinates. Location coordinates are shared with Google to fetch map tiles, subject to the Google Privacy Policy.\n"
                "• Google Play Services: Used for app delivery, updates, and core Android platform functionality.\n\n"
                "We may also disclose your information if required to do so by law, or in the good faith belief that such action is necessary to comply with legal obligations, protect our rights, or protect the safety of our users.",
                subTextColor,
              ),

              _buildSectionTitle("5. Publicly Visible User Information", textColor),
              _buildSectionContent(
                "Please note that certain elements of your user profile and activity are public by default to support the social features of the App:\n"
                "• Your username, display name, and profile photo.\n"
                "• Any road condition updates (\"Jump Posts\") you publish, including location details and attached photos/videos.\n"
                "• Comments, replies, and list statistics (such as follower counts).",
                subTextColor,
              ),

              _buildSectionTitle("6. Data Security and International Transfers", textColor),
              _buildSectionContent(
                "Your information is stored and processed on servers managed by our backend provider (Supabase). We enforce industry-standard security measures, including secure socket layers (SSL/TLS) for data in transit and encryption at rest.\n\n"
                "Please be aware that your data may be transferred to and maintained on servers located outside of your state, province, or country, where data protection laws may differ. By using the App, you consent to these international data transfers.",
                subTextColor,
              ),

              _buildSectionTitle("7. Data Retention and Account Deletion", textColor),
              _buildSectionContent(
                "We retain your Personal Data only for as long as your account is active or as needed to provide you with the Service.\n\n"
                "In accordance with Google Play's User Data policy regarding account deletion:\n"
                "1. How to delete your account: You can permanently delete your account directly inside the App by navigating to Settings > Account Information > Delete Account.\n"
                "2. Web-Based Deletion Request: If you cannot access the App, you can request account deletion by emailing us at tusiyeapp@gmail.com.\n"
                "3. Data Deletion Effects: Once you request deletion, we will permanently purge your profile data, personal identifiers, and account credentials from our active systems. Any posts, comments, or media you have published will be deleted or irreversibly anonymized.",
                subTextColor,
              ),

              _buildSectionTitle("8. Your Data Protection Rights (GDPR & CCPA)", textColor),
              _buildSectionContent(
                "Depending on your location, you may have the following data protection rights:\n"
                "• The Right to Access and Portability: You have the right to request copies of your Personal Data in a structured, machine-readable format.\n"
                "• The Right to Rectification: You have the right to request that we correct any inaccurate or incomplete Personal Data.\n"
                "• The Right to Erasure (The \"Right to be Forgotten\"): You have the right to request that we erase your Personal Data under certain conditions.\n"
                "• The Right to Restrict or Object to Processing: You have the right to object to our processing of your Personal Data or ask us to restrict its processing.\n"
                "• The Right to Withdraw Consent: You can withdraw your consent for location and media permissions at any time through your device settings.\n\n"
                "To exercise any of these rights, please contact us at tusiyeapp@gmail.com.",
                subTextColor,
              ),

              _buildSectionTitle("9. Children's Privacy", textColor),
              _buildSectionContent(
                "Our Service is not directed to individuals under the age of 13. We do not knowingly collect Personal Data from children under 13. If you become aware that a child has provided us with Personal Data without parental consent, please contact us immediately, and we will take immediate steps to remove such data from our servers.",
                subTextColor,
              ),

              _buildSectionTitle("10. Changes to This Privacy Policy", textColor),
              _buildSectionContent(
                "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the updated Privacy Policy on this page and revising the \"Effective Date\" at the top of the policy. We encourage you to review this Privacy Policy periodically to stay informed about how we protect your information.",
                subTextColor,
              ),

              _buildSectionTitle("11. Contact Us", textColor),
              _buildSectionContent(
                "If you have any questions, concerns, or requests regarding this Privacy Policy, please contact us at:\n\n"
                "• Email: tusiyeapp@gmail.com\n"
                "• Developer Name: Tusiye App Team",
                subTextColor,
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title, Color textColor) {
    return Padding(
      padding: const EdgeInsets.only(top: 24, bottom: 8),
      child: Text(
        title,
        style: GoogleFonts.poppins(
          fontSize: 16,
          fontWeight: FontWeight.bold,
          color: textColor,
        ),
      ),
    );
  }

  Widget _buildSubSectionTitle(String title, Color textColor) {
    return Padding(
      padding: const EdgeInsets.only(top: 12, bottom: 6),
      child: Text(
        title,
        style: GoogleFonts.poppins(
          fontSize: 14,
          fontWeight: FontWeight.w600,
          color: textColor,
        ),
      ),
    );
  }

  Widget _buildSectionContent(String content, Color textColor) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Text(
        content,
        style: GoogleFonts.poppins(
          fontSize: 14,
          color: textColor,
          height: 1.6,
        ),
      ),
    );
  }
}
