-- 1. Create a security definer function to delete the auth user
create or replace function public.handle_delete_user()
returns trigger as $$
begin
  delete from auth.users where id = old.id;
  return old;
end;
$$ language plpgsql security definer;

-- 2. Create an AFTER DELETE trigger on the profiles table
drop trigger if exists on_profile_deleted on public.profiles;
create trigger on_profile_deleted
  after delete on public.profiles
  for each row execute function public.handle_delete_user();

-- 3. Create content_reports table
create table if not exists public.content_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references public.profiles(id) on delete cascade not null,
  reported_post_id uuid references public.posts(id) on delete cascade,
  reported_comment_id uuid references public.comments(id) on delete cascade,
  reason text not null,
  details text,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'action_taken')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.content_reports enable row level security;

-- Policies for content_reports
drop policy if exists "Users can insert reports" on public.content_reports;
create policy "Users can insert reports" on public.content_reports 
  for insert with check (auth.uid() = reporter_id);

drop policy if exists "Admins can view and manage reports" on public.content_reports;
create policy "Admins can view and manage reports" on public.content_reports 
  for all using (
    exists (
      select 1 from public.profiles 
      where id = auth.uid() and is_admin = true
    )
  );

-- 4. Create user_blocks table
create table if not exists public.user_blocks (
  id bigint generated by default as identity primary key,
  blocker_id uuid references public.profiles(id) on delete cascade not null,
  blocked_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(blocker_id, blocked_id)
);

alter table public.user_blocks enable row level security;

-- Policies for user_blocks
drop policy if exists "Users can manage their own blocks" on public.user_blocks;
create policy "Users can manage their own blocks" on public.user_blocks 
  for all using (auth.uid() = blocker_id);

-- 5. Add DELETE policy on public.profiles to allow users to delete their own profiles
drop policy if exists "Users can delete own profile" on public.profiles;
create policy "Users can delete own profile" on public.profiles
  for delete using (auth.uid() = id);

-- 6. Adjust foreign keys on posts and comments to ON DELETE CASCADE
-- This ensures deleting a profile automatically deletes their posts and comments instead of causing a foreign key violation error.
alter table public.posts drop constraint if exists posts_author_id_fkey;
alter table public.posts add constraint posts_author_id_fkey 
  foreign key (author_id) references public.profiles(id) on delete cascade;

alter table public.comments drop constraint if exists comments_author_id_fkey;
alter table public.comments add constraint comments_author_id_fkey 
  foreign key (author_id) references public.profiles(id) on delete cascade;


