-- 1. ADD COLUMNS TO PROFILES IF THEY DON'T EXIST
alter table public.profiles add column if not exists is_admin boolean default false;
alter table public.profiles add column if not exists status text default 'active' check (status in ('active', 'suspended'));

-- 2. CREATE BANNERS TABLE FOR SYSTEM ANNOUNCEMENTS
create table if not exists public.app_banners (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  severity text not null default 'info' check (severity in ('info', 'warning', 'critical')),
  is_active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references public.profiles(id) on delete set null
);

-- ENABLE ROW LEVEL SECURITY
alter table public.app_banners enable row level security;

-- 3. POLICIES (Drop first to avoid conflicts)
drop policy if exists "Anyone can view active banners" on public.app_banners;
drop policy if exists "Admins can manage banners" on public.app_banners;

create policy "Anyone can view active banners" on public.app_banners 
  for select using (is_active = true);

create policy "Admins can manage banners" on public.app_banners 
  for all using (
    exists (
      select 1 from public.profiles 
      where id = auth.uid() and is_admin = true
    )
  );

-- 4. UPDATE EXISTING POLICIES TO ALLOW ADMIN TO DELETE/UPDATE CONTENT
-- Ensure admins can delete any posts
drop policy if exists "Admins can delete any post" on public.posts;
create policy "Admins can delete any post" on public.posts
  for delete using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

-- Ensure admins can delete any comment
drop policy if exists "Admins can delete any comment" on public.comments;
create policy "Admins can delete any comment" on public.comments
  for delete using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

-- Ensure admins can view and manage all profiles
drop policy if exists "Admins can update any profile" on public.profiles;
create policy "Admins can update any profile" on public.profiles
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

-- 5. SECURE ADMIN AND BAN STATUS WITH A DATABASE TRIGGER
-- Prevents standard users from promoting themselves to admin or unsuspending themselves.
create or replace function public.check_user_privileges_on_update()
returns trigger as $$
begin
  -- Check if the trigger is running for the user updating their own profile
  if auth.uid() = new.id then
    -- Non-admin cannot promote themselves to admin
    if old.is_admin = false and new.is_admin = true then
      -- Verify if the current session belongs to an existing admin doing the change
      if not exists (select 1 from public.profiles where id = auth.uid() and is_admin = true) then
        raise exception 'Access Denied: You cannot make yourself an admin.';
      end if;
    end if;

    -- Standard user cannot unsuspend themselves if they are suspended
    if old.status = 'suspended' and new.status = 'active' then
      if not exists (select 1 from public.profiles where id = auth.uid() and is_admin = true) then
        raise exception 'Access Denied: You cannot unsuspend your own account.';
      end if;
    end if;
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists enforce_profile_security on public.profiles;
create trigger enforce_profile_security
  before update on public.profiles
  for each row execute function public.check_user_privileges_on_update();

-- 6. BOOTSTRAP: PROMOTING THE SPECIFIED USER TO ADMIN
-- Email of the admin user: sakariyejabshe@gmail.com
update public.profiles 
set is_admin = true 
where id in (
  select id from auth.users 
  where email = 'sakariyejabshe@gmail.com'
) 
or name ilike 'sakariye%';
