-- 1. TABLES (Safe Creation)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  profile_image text,
  bio text,
  followers_count integer default 0,
  following_count integer default 0,
  posts_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) not null,
  road_name text,
  description text,
  image_url text,
  video_url text,
  likes_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) not null,
  author_id uuid references public.profiles(id) not null,
  text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. ENABLE RLS
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;

-- 3. POLICIES (Drop first to avoid conflicts)

-- PROFILES
drop policy if exists "Public profiles are viewable by everyone" on profiles;
drop policy if exists "Users can insert their own profile" on profiles;
drop policy if exists "Users can update own profile" on profiles;

create policy "Public profiles are viewable by everyone" on profiles for select using ( true );
create policy "Users can insert their own profile" on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile" on profiles for update using ( auth.uid() = id );

-- POSTS
drop policy if exists "Anyone can view posts" on posts;
drop policy if exists "Authenticated users can create posts" on posts;

create policy "Anyone can view posts" on posts for select using ( true );
create policy "Authenticated users can create posts" on posts for insert with check ( auth.role() = 'authenticated' );

-- COMMENTS
drop policy if exists "Anyone can view comments" on comments;
drop policy if exists "Authenticated users can create comments" on comments;

create policy "Anyone can view comments" on comments for select using ( true );
create policy "Authenticated users can create comments" on comments for insert with check ( auth.role() = 'authenticated' );

-- 4. STORAGE BUCKETS
insert into storage.buckets (id, name, public) values ('post-media', 'post-media', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true) on conflict (id) do nothing;

-- 5. STORAGE POLICIES
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access" on storage.objects for select using ( bucket_id in ('post-media', 'avatars') );

drop policy if exists "Authenticated users can upload" on storage.objects;
create policy "Authenticated users can upload" on storage.objects for insert with check ( auth.role() = 'authenticated' );
