-- 1. Create post_likes table
drop table if exists public.post_likes cascade;
create table public.post_likes (
  id bigint generated by default as identity primary key,
  post_id uuid references public.posts(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, user_id)
);

alter table public.post_likes enable row level security;

drop policy if exists "Anyone can view likes" on post_likes;
drop policy if exists "Authenticated users can like posts" on post_likes;
drop policy if exists "Users can unlike posts" on post_likes;

create policy "Anyone can view likes" on post_likes for select using ( true );
create policy "Authenticated users can like posts" on post_likes for insert with check ( auth.uid() = user_id );
create policy "Users can unlike posts" on post_likes for delete using ( auth.uid() = user_id );

-- 2. Create follows table
drop table if exists public.follows cascade;
create table public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid references public.profiles(id) on delete cascade not null,
  following_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(follower_id, following_id)
);

alter table public.follows enable row level security;

drop policy if exists "Anyone can view follows" on follows;
drop policy if exists "Authenticated users can follow" on follows;
drop policy if exists "Users can unfollow" on follows;

create policy "Anyone can view follows" on follows for select using ( true );
create policy "Authenticated users can follow" on follows for insert with check ( auth.uid() = follower_id );
create policy "Users can unfollow" on follows for delete using ( auth.uid() = follower_id );

-- 3. Add comments_count to posts
alter table public.posts add column if not exists comments_count integer default 0;

-- 4. Triggers to maintain likes_count on posts
create or replace function public.handle_like()
returns trigger as $$
begin
  if (tg_op = 'INSERT') then
    update public.posts set likes_count = likes_count + 1 where id = new.post_id;
    return new;
  elsif (tg_op = 'DELETE') then
    update public.posts set likes_count = likes_count - 1 where id = old.post_id;
    return old;
  end if;
  return null;
end;
$$ language plpgsql security definer;

drop trigger if exists on_like_created on public.post_likes;
create trigger on_like_created
  after insert or delete on public.post_likes
  for each row execute function public.handle_like();

-- 5. Triggers to maintain comments_count on posts
create or replace function public.handle_comment()
returns trigger as $$
begin
  if (tg_op = 'INSERT') then
    update public.posts set comments_count = comments_count + 1 where id = new.post_id;
    return new;
  elsif (tg_op = 'DELETE') then
    update public.posts set comments_count = comments_count - 1 where id = old.post_id;
    return old;
  end if;
  return null;
end;
$$ language plpgsql security definer;

drop trigger if exists on_comment_created on public.comments;
create trigger on_comment_created
  after insert or delete on public.comments
  for each row execute function public.handle_comment();

-- 6. Triggers to maintain followers_count and following_count
create or replace function public.handle_follow()
returns trigger as $$
begin
  if (tg_op = 'INSERT') then
    update public.profiles set followers_count = followers_count + 1 where id = new.following_id;
    update public.profiles set following_count = following_count + 1 where id = new.follower_id;
    return new;
  elsif (tg_op = 'DELETE') then
    update public.profiles set followers_count = followers_count - 1 where id = old.following_id;
    update public.profiles set following_count = following_count - 1 where id = old.follower_id;
    return old;
  end if;
  return null;
end;
$$ language plpgsql security definer;

drop trigger if exists on_follow_created on public.follows;
create trigger on_follow_created
  after insert or delete on public.follows
  for each row execute function public.handle_follow();

-- 7. Triggers to maintain posts_count on profiles
create or replace function public.handle_post()
returns trigger as $$
begin
  if (tg_op = 'INSERT') then
    update public.profiles set posts_count = posts_count + 1 where id = new.author_id;
    return new;
  elsif (tg_op = 'DELETE') then
    update public.profiles set posts_count = posts_count - 1 where id = old.author_id;
    return old;
  end if;
  return null;
end;
$$ language plpgsql security definer;

-- Also need to adjust comments foreign key to ON DELETE CASCADE
alter table public.comments drop constraint if exists comments_post_id_fkey;
alter table public.comments add constraint comments_post_id_fkey foreign key (post_id) references public.posts(id) on delete cascade;

drop trigger if exists on_post_created on public.posts;
create trigger on_post_created
  after insert or delete on public.posts
  for each row execute function public.handle_post();

-- 8. Create notifications table
drop table if exists public.notifications cascade;
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null, -- The user receiving the notification
  sender_id uuid references public.profiles(id) on delete cascade not null, -- The user who triggered the notification
  type text not null check (type in ('like', 'comment', 'follow')),
  post_id uuid references public.posts(id) on delete cascade, -- Nullable for follow notifications
  is_read boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.notifications enable row level security;

drop policy if exists "Users can view own notifications" on notifications;
drop policy if exists "System can insert notifications" on notifications;
drop policy if exists "Users can update own notifications" on notifications;

create policy "Users can view own notifications" on notifications for select using ( auth.uid() = user_id );
create policy "System can insert notifications" on notifications for insert with check (true);
create policy "Users can update own notifications" on notifications for update using ( auth.uid() = user_id );

-- 9. Triggers to create notifications
create or replace function public.create_notification_on_like()
returns trigger as $$
declare
  post_author uuid;
begin
  -- Get the author of the post
  select author_id into post_author from public.posts where id = new.post_id;
  
  -- Don't notify if liking own post
  if post_author != new.user_id then
    insert into public.notifications (user_id, sender_id, type, post_id)
    values (post_author, new.user_id, 'like', new.post_id);
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_like_notification on public.post_likes;
create trigger on_like_notification
  after insert on public.post_likes
  for each row execute function public.create_notification_on_like();

create or replace function public.create_notification_on_comment()
returns trigger as $$
declare
  post_author uuid;
begin
  select author_id into post_author from public.posts where id = new.post_id;
  
  if post_author != new.author_id then
    insert into public.notifications (user_id, sender_id, type, post_id)
    values (post_author, new.author_id, 'comment', new.post_id);
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_comment_notification on public.comments;
create trigger on_comment_notification
  after insert on public.comments
  for each row execute function public.create_notification_on_comment();

create or replace function public.create_notification_on_follow()
returns trigger as $$
begin
  insert into public.notifications (user_id, sender_id, type)
  values (new.following_id, new.follower_id, 'follow');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_follow_notification on public.follows;
create trigger on_follow_notification
  after insert on public.follows
  for each row execute function public.create_notification_on_follow();
